service: sls-chat-server

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

  stage: dev
  region: ap-southeast-1

  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-python-requirements

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
